### ISSUE TITLE
30 PCA components contains very small percentage of variance

### ISSUE THREAD

**Issue by vladimirkovacevic** [RixRasa/Genomics#2]
Huge amount of information is lost due to working with only 30 PCA components. Consider applying different methods for dimensionality reduction.

**Comment by DDeki** [comment]
Hello,
Following your advice, we have conducted extensive experiments with various dimensionality reduction techniques, generating between 50 and 200 components. Despite these efforts, we were unable to achieve better results compared to those obtained using the PCA method with 30 to 50 components.

The techniques we explored and tested include:
Truncated Singular Value Decomposition (TSVD)
Independent Component Analysis (ICA)
Non-negative Matrix Factorization (NMF)
t-Distributed Stochastic Neighbor Embedding (t-SNE)
Autoencoders in TensorFlow

Based on our comprehensive analysis and experimentation, we have determined that using 30 to 50 PCA components provides the optimal number for the best results in our case.

Thank you for your guidance.
